Traceback (most recent call last):
  File "C:\Users\paulj\AppData\Local\Programs\Python\Python311\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\paulj\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paulj\AppData\Local\Programs\Python\Python311\Lib\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paulj\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\paulj\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\paulj\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\paulj\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
'''
This python script opens a file named urls.txt in the  current folder and
downloads each url sequentually. Downloaded files are saved into the current folder.

Requirements
* In urls.txt URLs must be one per line and no line can be blank
* The URL must not use GET parameters (e.g. http://server/retrieve?file=myfile)
* urls.txt must be stored in the same folder as this file
* You must have read and write permission to this folder

v2.0 : 04/06/22
Additional function to allow selection of file save location
'''

import os
import urllib.request

#Links moved above the chdir, to ensure it can be in the current location
#Could just add it to the path...
links = open('urls.txt', 'r')

# Addition of where to save the file(s)
save_location = input("Hello. Where would you like to store the files [leave empty for current directory]:")
if (save_location == ""):
    save_location = os.getcwd()
    
os.chdir(save_location)

for link in links:

    #Get one line of text (e.g. http://server/files/grades.doc),
    # then get the filename from the end of the URL
    link = link.strip()
    filename = link.rsplit('/', 1)[-1]

    #Does this file exist in this folder? If not, download it
    if not (os.path.isfile(filename)):
        #print('Downloading: ' + filename )
        print("Downloading", link, "and saving as", save_location+filename)
        try:
            urllib.request.urlretrieve(link, filename)
            print("File size was", os.path.getsize(filename))
        except Exception as inst:
            print(inst)
            print('  Encountered unknown error. Continuing.')
    
    #File exists; don't download
    else:
        print("This file exists already.")

#End of program
print("Finished downloading.")
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [1;32mIn[1], line 20[0m
[0;32m     16[0m [38;5;28;01mimport[39;00m [38;5;21;01murllib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mrequest[39;00m
[0;32m     18[0m [38;5;66;03m#Links moved above the chdir, to ensure it can be in the current location[39;00m
[0;32m     19[0m [38;5;66;03m#Could just add it to the path...[39;00m
[1;32m---> 20[0m links [38;5;241m=[39m [38;5;28;43mopen[39;49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43murls.txt[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mr[39;49m[38;5;124;43m'[39;49m[43m)[49m
[0;32m     22[0m [38;5;66;03m# Addition of where to save the file(s)[39;00m
[0;32m     23[0m save_location [38;5;241m=[39m [38;5;28minput[39m([38;5;124m"[39m[38;5;124mHello. Where would you like to store the files [leave empty for current directory]:[39m[38;5;124m"[39m)

File [1;32m~\AppData\Local\Programs\Python\Python311\Lib\site-packages\IPython\core\interactiveshell.py:284[0m, in [0;36m_modified_open[1;34m(file, *args, **kwargs)[0m
[0;32m    277[0m [38;5;28;01mif[39;00m file [38;5;129;01min[39;00m {[38;5;241m0[39m, [38;5;241m1[39m, [38;5;241m2[39m}:
[0;32m    278[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[0;32m    279[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mIPython won[39m[38;5;124m'[39m[38;5;124mt let you open fd=[39m[38;5;132;01m{[39;00mfile[38;5;132;01m}[39;00m[38;5;124m by default [39m[38;5;124m"[39m
[0;32m    280[0m         [38;5;124m"[39m[38;5;124mas it is likely to crash IPython. If you know what you are doing, [39m[38;5;124m"[39m
[0;32m    281[0m         [38;5;124m"[39m[38;5;124myou can use builtins[39m[38;5;124m'[39m[38;5;124m open.[39m[38;5;124m"[39m
[0;32m    282[0m     )
[1;32m--> 284[0m [38;5;28;01mreturn[39;00m [43mio_open[49m[43m([49m[43mfile[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'urls.txt'

